services:
  search_api:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file: .env
    ports:
      - "8001:8000"
    environment:
      - QDRANT_HOST=${QDRANT_HOST}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT}
      - DEBUG=${DEBUG}
    restart: unless-stopped
